### PR TITLE
Added post-processor option as per #262

### PR DESCRIPTION
**Pull request by mastef**
See #262. If `postProcessor` option is defined, the command will be run after each `.hx` file is generated.

### CODE REVIEW

**Comment by mastef** [comment]
The CI seems to break based on the haxe dev config, not this PR. haxe 3.4.2 passes

**Comment by andyli** [comment]
The CI issue was fixed in https://github.com/HaxeFoundation/as3hx/commit/9ebb3531a5a05e40dbfd005e5597e95dec32054e, you may rebase on top of it and force push to trigger a new build for this PR.

**Comment by mastef** [comment]
OK did a rebase : 
```
git remote add upstream https://github.com/HaxeFoundation/as3hx.git
git fetch upstream
git checkout master
git rebase upstream/master
git push -f origin master
```

**Comment by mastef** [comment]
@SlavaRa @andyli that PR cool with you?

**Comment by andyli** [comment]
I'll let @SlavaRa review and decide :)

**Pull request merged**
