### PR TITLE
fixes issue #56

### PR DESCRIPTION
**Pull request by SlavaRa**

### CODE REVIEW

**Comment by SlavaRa** [comment]
please merge this PR before https://github.com/HaxeFoundation/as3hx/pull/61

**Comment by Simn** [comment]
I have no idea what TNL is, so the natural question is if there could be something like `TNL(TNL(TId(_)))`. Shouldn't we recurse properly here?

**Comment by SlavaRa** [comment]
No, I checked out .. but I can try to add test cases to avoid any such issues.
But I can not estimate how long it will take

**Comment by Simn** [comment]
Ah TNL is newline... Looking at the tokenizer (https://github.com/HaxeFoundation/as3hx/blob/master/src/as3hx/Tokenizer.hx#L125) I don't see what would prevent a nested `TNL(TNL(_))` so I really think this has to be handled differently.

**Comment by SlavaRa** [comment]
hm... i check this

**Comment by SlavaRa** [comment]
@Simn fixed

**Comment by Simn** [comment]
@ncannasse: Do you remember why `TNL` exists at all? I have no idea in which cases it can/should be skipped.

**Comment by SlavaRa** [comment]
Token New Line
```var o:Object = {
  x : 1
}```
1 - TNL

```var o:Object = {

  x : 1
}```
2 - TNL


```var o:Object = {
  ...
  x : 1
}```
N - TNL

**Comment by ncannasse** [comment]
I honestly can't remember, might have been a trick to deal with significant newlines

**Comment by SlavaRa** [comment]
guys that I should do?

**Comment by nadako** [comment]
It looks like there's noone maintaining this repository at the moment, so @SlavaRa, do you think you could take care of it? What do you guys think, @Simn, @ncannasse?

Regarding the PRs, it looks like this project actually has tests, so adding test cases for the fixed issues would be great.

**Comment by SlavaRa** [comment]
I could fix most of the bugs and do it quickly, but I need someone to do review.

**Comment by nadako** [comment]
> someone to do review.

I think we have a problem with exactly that, that's why I suggested you taking over of the tool.

**Comment by SlavaRa** [comment]
if no other choice, I agree

**Comment by SlavaRa** [comment]
@Simn @ncannasse @nadako @andyli @waneck guys what about this PR?

**Comment by nadako** [comment]
I really don't know, I think we should decide on a new maintainer for this.

**Pull request merged**
