### PR TITLE
fixes issue #58

### PR DESCRIPTION
**Pull request by SlavaRa**

### CODE REVIEW

**Comment by SlavaRa** [comment]
@Simn please review and merge this PR, https://github.com/HaxeFoundation/as3hx/pull/60, https://github.com/HaxeFoundation/as3hx/pull/61 and I will make more PR

**Comment by Simn** [comment]
I don't understand what passing `conds` around is supposed to do. From what I can tell it's never modified anyway...

**Comment by SlavaRa** [comment]
if coonds not contain elements, then use a while loop
issue https://github.com/HaxeFoundation/as3hx/issues/58

**Comment by Simn** [comment]
Yes but why add it as a function argument?

**Comment by SlavaRa** [comment]
i don't know, by design, maybe)

**Pull request merged**
