### PR TITLE
 Fixed conversion of 'array[index]['key']'. fixes #261

### LINKED ISSUE #261: Assigning to anonymous object in an array, index expression confused with RHS
Under some conditions, assigning values to an anonymous object in an array using an index into the array, the index values are being assigned instead of the actual right-hand values.

as3 code for example:
```actionscript
package {
    public class Issue {
        public function Issue() {
            //code here...
            var arr:Array = [];
            arr.push(new Data());
            arr.push(new Data());
         
            var chains:Array = [];
            for each (var data:Data in arr) {
              if (data.value==1) continue;
              // Push an object into chains
              chains.push({
                min_value: data.value,
                names: [ data.toString() ]
              });
              // - - - Here are the lines showing the issue - - -
              chains[chains.length-1]["number"] = 555;
              chains[chains.length-2]["data"] = data;
              chains[chains.length-3]["as_array"] = [data];
              // - - - - - - - - - - - - - - - - - - - - - - - -
            }
        }
    }
}

class Data {
  public var value:int;
  public function Data():void {
    value = Math.random()*1000;
  }
  public function toString():String { return '[Data:'+value+']'; }
}
```

Expected result:
```haxe
...
// - - - Here are the lines showing the issue - - -
Reflect.setField(chains[chains.length - 1], "number", 555);
Reflect.setField(chains[chains.length - 2], "data", data);
Reflect.setField(chains[chains.length - 3], "as_array", [data]);
...
```

Actual result:
```haxe
...
// - - - Here are the lines showing the issue - - -
Reflect.setField(chains[chains.length - 1], "number", 1);
Reflect.setField(chains[chains.length - 2], "data", 2);
Reflect.setField(chains[chains.length - 3], "as_array", 3);
...
```

The expression in the array index is somehow polluting the RHS value.

### PR DESCRIPTION
**Pull request by SlavaRa**

### CODE REVIEW

**Comment by Kendja** [comment]
@SlavaRa 
Looks like this change(https://github.com/HaxeFoundation/as3hx/commit/8d68b42037295a8dbe42013759f31cf03eaa5e2b#diff-8f512c0986dbff22af802aba4b7463e3R2192) breaks this code:

original as3:
```as3
      // case 1
      public function randomGen(param1:int) : int
      {
         var _loc2_:int = Math.floor(Math.random() * param1);
         return _loc2_;
      }
      
      // case 2
      function frame1() : *
      {
         gotoAndPlay((this.randomGen(48) + 1) * 4 + 1);
      }
```

expected result:
```haxe
    // case 1
    public function randomGen(param1 : Int) : Int
    {
        var _loc2_ : Int = Math.floor(Math.random() * param1);
        return _loc2_;
    }
    
    // case 2
    private function frame1() : Dynamic
    {
        gotoAndPlay((this.randomGen(48) + 1) * 4 + 1);
    }
```

actual result
```haxe
    // case 1
    public function randomGen(param1 : Int) : Int
    {
        var _loc2_ : Int = Math.floor(Math.random());
        return _loc2_;
    }
    
    // case 2
    private function frame1() : Dynamic
    {
        gotoAndPlay((this.randomGen(48)));
    }
```

**Comment by SlavaRa** [comment]
Thanks. I will check and let you know

**Comment by SlavaRa** [comment]
@Kendja fixed

**Comment by Kendja** [comment]
@SlavaRa nice! 💪

**Pull request merged**
