### PR TITLE
remove redundant test targets

### PR DESCRIPTION
**Pull request by SlavaRa**

### CODE REVIEW

**Comment by andyli** [comment]
I don't think they're really redundant. At least compiling to cpp is reasonable when processing a large code base. Try not to remove existing tests, please. ;)

**Comment by SlavaRa** [comment]
ok, but cpp target not working for Haxe Development

**Comment by SlavaRa** [comment]
Flash, JS can not be the purpose of testing

**Comment by andyli** [comment]
We can see that it is not likely an issue from the as3hx code base since Haxe 3.2.1 compiles and run correctly. So it is most likely an hxcpp issue. In this case we need to report to hxcpp, so let's ping @hughsando:

The unit test here uses munit 2.1.2, and it gives [an error as follows](https://travis-ci.org/HaxeFoundation/as3hx/jobs/149767986#L238-L244)
```
HaxeWrapper.hx:73: Error: While running :g++ -I/home/travis/build/HaxeFoundation/as3hx/build/cpp_test/obj/linux64/__pch/haxe -Iinclude -c -fvisibility=hidden -O2 -fpic -fPIC -DHX_LINUX -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS -DHXCPP_API_LEVEL=330 -m64 -DHXCPP_M64 -I/home/travis/haxe/lib/hxcpp/3,3,49/include -x c++ -frtti -Wno-invalid-offsetof ./src/massive/munit/client/RichPrintClient.cpp -o/home/travis/build/HaxeFoundation/as3hx/build/cpp_test/obj/linux64/16f61629_RichPrintClient.o
HaxeWrapper.hx:73: ./src/massive/munit/client/RichPrintClient.cpp: In member function ‘virtual void massive::munit::client::RichPrintClient_obj::updateTestClass(massive::munit::TestResult)’:
HaxeWrapper.hx:73: ./src/massive/munit/client/RichPrintClient.cpp:113:53: error: ‘_hx_getEnumValueIndex’ was not declared in this scope
HaxeWrapper.hx:73: ./src/massive/munit/client/RichPrintClient.cpp: In member function ‘virtual void massive::munit::client::RichPrintClient_obj::finalizeTestClass()’:
HaxeWrapper.hx:73: ./src/massive/munit/client/RichPrintClient.cpp:190:75: error: ‘_hx_getEnumValueIndex’ was not declared in this scope
HaxeWrapper.hx:73: Error: Build failed
Error: Error compiling hxml for cpp
```

For Flash and JS, although we do not run the compilation output, we at least verify that the code base is compilable to those targets.

**Comment by SlavaRa** [comment]
ok ;)

**Comment by hughsando** [comment]
Not sure if you solved it, but it needs the bleeding-edge hxcpp if you are using bleeding-edge haxe.

**Comment by andyli** [comment]
Ah, indeed. Though I've already done that when I setup Travis for this repo. Fixed in 6af06d9b0d9126f27cd4b66945095b284168f83c. Thanks!

**Pull request closed without merging**
